# Generated by Django 5.2 on 2025-05-05 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_delete_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phonenumber',
            new_name='message',
        ),
    ]
