# Generated by Django 5.2 on 2025-05-05 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_phone_user_service_alter_user_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='service',
            new_name='position',
        ),
    ]
