# Generated by Django 5.2 on 2025-05-05 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_service_user_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='position',
            new_name='services',
        ),
    ]
